"""Depend

Revision ID: df22370f704b
Revises: f9efc9bd73f3
Create Date: 2023-09-14 16:27:37.657679

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df22370f704b'
down_revision: Union[str, None] = 'f9efc9bd73f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'credits', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'payments', 'credits', ['credit_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'payments', 'dictionary', ['type_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'plans', 'dictionary', ['category_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'plans', type_='foreignkey')
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.drop_constraint(None, 'credits', type_='foreignkey')
    # ### end Alembic commands ###
